bike <- read.csv('bikeshare.csv')
head(bike)
library(ggplot2)
pl <- ggplot(bike, aes(x= temp, y= count))
library(RColorBrewer)
pl <- pl + geom_point(aes(color=temp), alpha= 0.5) + theme_bw()
print(pl)
bike$datetime <- as.POSIXct(bike$datetime)
bike <- bike[,-13]
pl1 <- ggplot(bike, aes(x=datetime, y= count ))
pl1 <- pl1 + geom_point(aes(color=temp), alpha=0.5) + scale_color_gradient(low= "#91DAF2", high="#F09351")
print(pl1)
cor(bike$temp, bike$count)
cor(bike[,c("temp","count")]) #will give the correlation matrix
pl2 <- ggplot(bike, aes(x= factor(season),y=count))
pl2 <- pl2 + geom_boxplot(aes(color=factor(season)))
print(pl2)
bike$hour <- sapply(bike$datetime,function(x){format(x,"%H")})
pl3 <- ggplot(subset(bike, workingday == 1), aes(x= hour, y= count))
pl3 <- pl3 + geom_point(aes(color=temp), alpha = 0.5, position=position_jitter(w=1, h=0)) + scale_color_gradient(low= "#91DAF2", high="#F09351")
print(pl3)
pl4 <- ggplot(subset(bike, workingday == 0), aes(x= hour, y= count))
pl4 <- pl4 + geom_point(aes(color=temp), alpha = 0.5, position=position_jitter(w=1, h=0)) + scale_color_gradient(low= "#91DAF2", high="#F09351")
print(pl4)

#the model
model <- lm(count ~ temp, bike)
summary(model)
6.042 + 9.1705*25 #prediction for temp = 25
bike$hour <- sapply(bike$hour, function(x){as.numeric(x)})
newmodel <- lm(count~season+holiday+ workingday +weather+temp+humidity +windspeed+hour, bike)
summary(newmodel)
cor(bike$holiday,bike$workingday)
newmodel1 <- lm(count~season+ workingday +weather+temp+humidity +windspeed+hour, bike)
summary(newmodel1)
